[package]
name = "rustchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.1.1"
sha256 = "1.0.3"
rocket = "0.4.10"
serde = "1.0.137"
serde_json = "1.0.81"
lazy_static = "1.3.0"